version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./driving_school.db
      - LOG_LEVEL=DEBUG
    command: poetry run python -m ontario_driving_school_manager 